twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  enable-mock-tweets: true
  mock-tweet-min-length: 5
  mock-tweet-max-length: 15
  mock-sleep-ms: 10000