server:
  port: 8888

logging:
  level:
    root: info
    org.springframework.cloud.config: debug

spring:
#  profiles:
#    active: native
  application:
    name: configserver
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///D:/PROJECTS/microservices-demo/config-server-repository
        git:
          uri: https://github.com/1or1is1/spring-cloud-config-server-repository
          default-label: master
          force-pull: true
      fail-fast: true